workers_dev = true
name = "airtheon-web"
compatibility_date = "2025-02-16"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "airbase"
database_id = "8a28a618-9a3f-49e3-879d-540d0eaabf1e"

[[r2_buckets]]
bucket_name = "airstore"
binding = "airstore"