workers_dev = true
name = "react-router-cloudflare-saas-kit"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "saas-data-store"
database_id = "5aeb8148-32bc-44ee-9e21-a849756467a7"